<a href="https://colab.research.google.com/github/Carrinson/collab-files/blob/main/Regression_with_Keras_py_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [115]:
# All Libraries required for this lab are listed below. The libraries pre-installed on Skills Network Labs are commented.
# If you run this notebook on a different environment, e.g. your desktop, you may need to uncomment and install certain libraries.
%pip install numpy==2.0.2
%pip install pandas==2.2.2
%pip install tensorflow keras

Requirement already satisfied: numpy==2.0.2 in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas==2.2.2 in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas==2.2.2) (1.17.0)
Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.20.0)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (3.13.2)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.2)
Requirement already satisfied: protobuf>=5.28.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.2.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.81.1)
Requirement already satisfied: tensorboard~=2.20.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.20.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras) (0.19.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.5.20)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.10.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.1.8)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)

In [116]:
import pandas as pd
import numpy as np
import keras
from sklearn.preprocessing import LabelEncoder


import warnings
warnings.simplefilter('ignore', FutureWarning)

In [117]:
filepath='/content/nigeria_houses_data.csv'
houses_data = pd.read_csv(filepath)

houses_data.head()

,bedrooms,bathrooms,toilets,parking_space,title,town,state,price
0,6.0,5.0,5.0,4.0,Detached Duplex,Mabushi,Abuja,450000000.0
1,4.0,5.0,5.0,4.0,Terraced Duplexes,Katampe,Abuja,800000000.0
2,4.0,5.0,5.0,4.0,Detached Duplex,Lekki,Lagos,120000000.0
3,4.0,4.0,5.0,6.0,Detached Duplex,Ajah,Lagos,40000000.0
4,4.0,4.0,5.0,2.0,Semi Detached Duplex,Lekki,Lagos,75000000.0

In [118]:
le = LabelEncoder()
houses_data['title']  = le.fit_transform(houses_data['title'] ) + 1
houses_data['town']  = le.fit_transform(houses_data['town'] ) + 1
houses_data['state']  = le.fit_transform(houses_data['state'] ) + 1

In [119]:
houses_data.head()

,bedrooms,bathrooms,toilets,parking_space,title,town,state,price
0,6.0,5.0,5.0,4.0,3,128,2,450000000.0
1,4.0,5.0,5.0,4.0,7,111,2,800000000.0
2,4.0,5.0,5.0,4.0,3,123,18,120000000.0
3,4.0,4.0,5.0,6.0,3,11,18,40000000.0
4,4.0,4.0,5.0,2.0,5,123,18,75000000.0

In [120]:
houses_data.shape

(24326, 8)

In [121]:
houses_data.describe()

,bedrooms,bathrooms,toilets,parking_space,title,town,state,price
count,24326.000000,24326.000000,24326.000000,24326.000000,24326.000000,24326.000000,24326.000000,2.432600e+04
mean,4.338814,4.600798,5.176355,4.041725,3.557552,101.793143,15.711625,3.013802e+08
std,1.138497,1.163161,1.226253,1.399936,1.644986,44.186951,6.024042,1.220403e+10
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,9.000000e+04
25%,4.000000,4.000000,5.000000,4.000000,3.000000,78.000000,18.000000,5.200000e+07
50%,4.000000,5.000000,5.000000,4.000000,3.000000,123.000000,18.000000,8.500000e+07
75%,5.000000,5.000000,6.000000,4.000000,4.000000,123.000000,18.000000,1.600000e+08
max,9.000000,9.000000,9.000000,9.000000,7.000000,189.000000,25.000000,1.800000e+12

In [122]:
houses_data.isnull().sum()

bedrooms         0
bathrooms        0
toilets          0
parking_space    0
title            0
town             0
state            0
price            0
dtype: int64

In [123]:
houses_data_columns = houses_data.columns
print(houses_data_columns)

Index(['bedrooms', 'bathrooms', 'toilets', 'parking_space', 'title', 'town',
       'state', 'price'],
      dtype='object')

In [124]:
houses_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24326 entries, 0 to 24325
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   bedrooms       24326 non-null  float64
 1   bathrooms      24326 non-null  float64
 2   toilets        24326 non-null  float64
 3   parking_space  24326 non-null  float64
 4   title          24326 non-null  int64
 5   town           24326 non-null  int64
 6   state          24326 non-null  int64
 7   price          24326 non-null  float64
dtypes: float64(5), int64(3)
memory usage: 1.5 MB

In [125]:
predictors = houses_data[houses_data_columns[houses_data_columns != 'price']] # all columns except Price
target = houses_data['price'] # Price column

<a id="item2"></a>

In [126]:
predictors.head()

   bedrooms  bathrooms  toilets  parking_space  title  town  state
0       6.0        5.0      5.0            4.0      3   128      2
1       4.0        5.0      5.0            4.0      7   111      2
2       4.0        5.0      5.0            4.0      3   123     18
3       4.0        4.0      5.0            6.0      3    11     18
4       4.0        4.0      5.0            2.0      5   123     18

In [127]:
target.head()

0    450000000.0
1    800000000.0
2    120000000.0
3     40000000.0
4     75000000.0
Name: price, dtype: float64

In [128]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

   bedrooms  bathrooms   toilets  parking_space     title      town     state
0  1.459103   0.343205 -0.143816      -0.029805 -0.338940  0.593090 -2.276150
1 -0.297598   0.343205 -0.143816      -0.029805  2.092692  0.208361 -2.276150
2 -0.297598   0.343205 -0.143816      -0.029805 -0.338940  0.479935  0.379874
3 -0.297598  -0.516521 -0.143816       1.398832 -0.338940 -2.054750  0.379874
4 -0.297598  -0.516521 -0.143816      -1.458441  0.876876  0.479935  0.379874

In [129]:
n_cols = predictors_norm.shape[1] # number of predictors

In [130]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Input

<a id='item33'></a>

In [131]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Input(shape=(n_cols,)))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))

    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [132]:
# build the model
model = regression_model()

In [133]:
# fit the model
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
533/533 - 6s - 11ms/step - loss: 212653430111226298368.0000 - val_loss: 557783554440822784.0000
Epoch 2/100
533/533 - 3s - 5ms/step - loss: 212653377334668165120.0000 - val_loss: 557783554440822784.0000
Epoch 3/100
533/533 - 4s - 8ms/step - loss: 212653482887784431616.0000 - val_loss: 557783520081084416.0000
Epoch 4/100
533/533 - 1s - 3ms/step - loss: 212653394926854209536.0000 - val_loss: 557783520081084416.0000
Epoch 5/100
533/533 - 2s - 4ms/step - loss: 212653412519040253952.0000 - val_loss: 557783348282392576.0000
Epoch 6/100
533/533 - 1s - 3ms/step - loss: 212653412519040253952.0000 - val_loss: 557783313922654208.0000
Epoch 7/100
533/533 - 1s - 2ms/step - loss: 212653359742482120704.0000 - val_loss: 557783142123962368.0000
Epoch 8/100
533/533 - 1s - 2ms/step - loss: 212653377334668165120.0000 - val_loss: 557783004685008896.0000
Epoch 9/100
533/533 - 1s - 2ms/step - loss: 212653465295598387200.0000 - val_loss: 557782867246055424.0000
Epoch 10/100
533/533 - 1s - 2ms/step - loss: 212653482887784431616.0000 - val_loss: 557782729807101952.0000
Epoch 11/100
533/533 - 1s - 2ms/step - loss: 212653482887784431616.0000 - val_loss: 557782558008410112.0000
Epoch 12/100
533/533 - 2s - 4ms/step - loss: 212653412519040253952.0000 - val_loss: 557782283130503168.0000
Epoch 13/100
533/533 - 2s - 4ms/step - loss: 212653412519040253952.0000 - val_loss: 557782008252596224.0000
Epoch 14/100
533/533 - 3s - 5ms/step - loss: 212653430111226298368.0000 - val_loss: 557781733374689280.0000
Epoch 15/100
533/533 - 2s - 5ms/step - loss: 212653359742482120704.0000 - val_loss: 557781458496782336.0000
Epoch 16/100
533/533 - 1s - 2ms/step - loss: 212653500479970476032.0000 - val_loss: 557781046179921920.0000
Epoch 17/100
533/533 - 2s - 3ms/step - loss: 212653447703412342784.0000 - val_loss: 557780805661753344.0000
Epoch 18/100
533/533 - 2s - 4ms/step - loss: 212653430111226298368.0000 - val_loss: 557780633863061504.0000
Epoch 19/100
533/533 - 1s - 3ms/step - loss: 212653482887784431616.0000 - val_loss: 557780255905939456.0000
Epoch 20/100
533/533 - 2s - 4ms/step - loss: 212653377334668165120.0000 - val_loss: 557779740509863936.0000
Epoch 21/100
533/533 - 1s - 2ms/step - loss: 212653465295598387200.0000 - val_loss: 557779122034573312.0000
Epoch 22/100
533/533 - 1s - 2ms/step - loss: 212653394926854209536.0000 - val_loss: 557778847156666368.0000
Epoch 23/100
533/533 - 1s - 2ms/step - loss: 212653394926854209536.0000 - val_loss: 557778366120329216.0000
Epoch 24/100
533/533 - 1s - 2ms/step - loss: 212653306965923987456.0000 - val_loss: 557777885083992064.0000
Epoch 25/100
533/533 - 1s - 2ms/step - loss: 212653447703412342784.0000 - val_loss: 557777232248963072.0000
Epoch 26/100
533/533 - 1s - 2ms/step - loss: 212653430111226298368.0000 - val_loss: 557776441974980608.0000
Epoch 27/100
533/533 - 1s - 2ms/step - loss: 212653465295598387200.0000 - val_loss: 557775926578905088.0000
Epoch 28/100
533/533 - 1s - 2ms/step - loss: 212653412519040253952.0000 - val_loss: 557775033225707520.0000
Epoch 29/100
533/533 - 2s - 4ms/step - loss: 212653394926854209536.0000 - val_loss: 557774586549108736.0000
Epoch 30/100
533/533 - 1s - 3ms/step - loss: 212653394926854209536.0000 - val_loss: 557773968073818112.0000
Epoch 31/100
533/533 - 1s - 2ms/step - loss: 212653377334668165120.0000 - val_loss: 557773177799835648.0000
Epoch 32/100
533/533 - 1s - 2ms/step - loss: 212653518072156520448.0000 - val_loss: 557772318806376448.0000
Epoch 33/100
533/533 - 1s - 2ms/step - loss: 212653500479970476032.0000 - val_loss: 557771425453178880.0000
Epoch 34/100
533/533 - 2s - 3ms/step - loss: 212653394926854209536.0000 - val_loss: 557770394661027840.0000
Epoch 35/100
533/533 - 1s - 2ms/step - loss: 212653377334668165120.0000 - val_loss: 557769295149400064.0000
Epoch 36/100
533/533 - 1s - 2ms/step - loss: 212653377334668165120.0000 - val_loss: 557768298716987392.0000
Epoch 37/100
533/533 - 1s - 3ms/step - loss: 212653447703412342784.0000 - val_loss: 557767645881958400.0000
Epoch 38/100
533/533 - 3s - 5ms/step - loss: 212653412519040253952.0000 - val_loss: 557766477650853888.0000
Epoch 39/100
533/533 - 1s - 2ms/step - loss: 212653377334668165120.0000 - val_loss: 557764931462627328.0000
Epoch 40/100
533/533 - 1s - 2ms/step - loss: 212653394926854209536.0000 - val_loss: 557763831950999552.0000
Epoch 41/100
533/533 - 1s - 2ms/step - loss: 212653430111226298368.0000 - val_loss: 557762560640679936.0000
Epoch 42/100
533/533 - 1s - 3ms/step - loss: 212653500479970476032.0000 - val_loss: 557761667287482368.0000
Epoch 43/100
533/533 - 1s - 2ms/step - loss: 212653289373737943040.0000 - val_loss: 557760258538209280.0000
Epoch 44/100
533/533 - 1s - 2ms/step - loss: 212653324558110031872.0000 - val_loss: 557758987227889664.0000
Epoch 45/100
533/533 - 1s - 2ms/step - loss: 212653201412807720960.0000 - val_loss: 557756891283849216.0000
Epoch 46/100
533/533 - 2s - 4ms/step - loss: 212653518072156520448.0000 - val_loss: 557755516894314496.0000
Epoch 47/100
533/533 - 2s - 3ms/step - loss: 212653324558110031872.0000 - val_loss: 557754073785303040.0000
Epoch 48/100
533/533 - 1s - 2ms/step - loss: 212653430111226298368.0000 - val_loss: 557752871194460160.0000
Epoch 49/100
533/533 - 1s - 2ms/step - loss: 212653412519040253952.0000 - val_loss: 557751153207541760.0000
Epoch 50/100
533/533 - 1s - 2ms/step - loss: 212653412519040253952.0000 - val_loss: 557749160342716416.0000
Epoch 51/100
533/533 - 1s - 2ms/step - loss: 212653271781551898624.0000 - val_loss: 557747373636321280.0000
Epoch 52/100
533/533 - 1s - 2ms/step - loss: 212653359742482120704.0000 - val_loss: 557745105893588992.0000
Epoch 53/100
533/533 - 1s - 2ms/step - loss: 212653306965923987456.0000 - val_loss: 557743594065100800.0000
Epoch 54/100
533/533 - 1s - 2ms/step - loss: 212653148636249587712.0000 - val_loss: 557741669919752192.0000
Epoch 55/100
533/533 - 2s - 4ms/step - loss: 212653236597179809792.0000 - val_loss: 557739505256235008.0000
Epoch 56/100
533/533 - 1s - 3ms/step - loss: 212653201412807720960.0000 - val_loss: 557737409312194560.0000
Epoch 57/100
533/533 - 1s - 2ms/step - loss: 212653324558110031872.0000 - val_loss: 557735622605799424.0000
Epoch 58/100
533/533 - 1s - 2ms/step - loss: 212653271781551898624.0000 - val_loss: 557733148704636928.0000
Epoch 59/100
533/533 - 1s - 2ms/step - loss: 212653236597179809792.0000 - val_loss: 557730915321643008.0000
Epoch 60/100
533/533 - 1s - 2ms/step - loss: 212653306965923987456.0000 - val_loss: 557728235262050304.0000
Epoch 61/100
533/533 - 1s - 2ms/step - loss: 212653324558110031872.0000 - val_loss: 557726208037486592.0000
Epoch 62/100
533/533 - 1s - 2ms/step - loss: 212653148636249587712.0000 - val_loss: 557723734136324096.0000
Epoch 63/100
533/533 - 1s - 2ms/step - loss: 212653219004993765376.0000 - val_loss: 557721122796208128.0000
Epoch 64/100
533/533 - 3s - 5ms/step - loss: 212653271781551898624.0000 - val_loss: 557718202218446848.0000
Epoch 65/100
533/533 - 1s - 2ms/step - loss: 212653095859691454464.0000 - val_loss: 557715625238069248.0000
Epoch 66/100
533/533 - 1s - 2ms/step - loss: 212653183820621676544.0000 - val_loss: 557713048257691648.0000
Epoch 67/100
533/533 - 1s - 2ms/step - loss: 212653219004993765376.0000 - val_loss: 557710265118883840.0000
Epoch 68/100
533/533 - 1s - 2ms/step - loss: 212653254189365854208.0000 - val_loss: 557707310181384192.0000
Epoch 69/100
533/533 - 1s - 2ms/step - loss: 212653306965923987456.0000 - val_loss: 557704492682838016.0000
Epoch 70/100
533/533 - 1s - 2ms/step - loss: 212653148636249587712.0000 - val_loss: 557700987989524480.0000
Epoch 71/100
533/533 - 1s - 2ms/step - loss: 212653007898761232384.0000 - val_loss: 557698376649408512.0000
Epoch 72/100
533/533 - 2s - 4ms/step - loss: 212653342150296076288.0000 - val_loss: 557695181193740288.0000
Epoch 73/100
533/533 - 2s - 3ms/step - loss: 212653131044063543296.0000 - val_loss: 557692157536763904.0000
Epoch 74/100
533/533 - 2s - 3ms/step - loss: 212653148636249587712.0000 - val_loss: 557688549764235264.0000
Epoch 75/100
533/533 - 1s - 2ms/step - loss: 212652919937831010304.0000 - val_loss: 557685045070921728.0000
Epoch 76/100
533/533 - 1s - 2ms/step - loss: 212653095859691454464.0000 - val_loss: 557681815255515136.0000
Epoch 77/100
533/533 - 1s - 2ms/step - loss: 212653131044063543296.0000 - val_loss: 557677554647957504.0000
Epoch 78/100
533/533 - 1s - 2ms/step - loss: 212653183820621676544.0000 - val_loss: 557674290472812544.0000
Epoch 79/100
533/533 - 1s - 2ms/step - loss: 212653113451877498880.0000 - val_loss: 557669720627609600.0000
Epoch 80/100
533/533 - 1s - 3ms/step - loss: 212653183820621676544.0000 - val_loss: 557666250294034432.0000
Epoch 81/100
533/533 - 2s - 4ms/step - loss: 212653007898761232384.0000 - val_loss: 557662333283860480.0000
Epoch 82/100
533/533 - 1s - 2ms/step - loss: 212653201412807720960.0000 - val_loss: 557657935237349376.0000
Epoch 83/100
533/533 - 1s - 2ms/step - loss: 212653025490947276800.0000 - val_loss: 557654499263512576.0000
Epoch 84/100
533/533 - 1s - 2ms/step - loss: 212652972714389143552.0000 - val_loss: 557649791979356160.0000
Epoch 85/100
533/533 - 1s - 2ms/step - loss: 212653095859691454464.0000 - val_loss: 557646115487350784.0000
Epoch 86/100
533/533 - 1s - 2ms/step - loss: 212653113451877498880.0000 - val_loss: 557641236404502528.0000
Epoch 87/100
533/533 - 1s - 2ms/step - loss: 212653007898761232384.0000 - val_loss: 557637078876160000.0000
Epoch 88/100
533/533 - 1s - 2ms/step - loss: 212653131044063543296.0000 - val_loss: 557632440311480320.0000
Epoch 89/100
533/533 - 1s - 2ms/step - loss: 212653148636249587712.0000 - val_loss: 557627251990986752.0000
Epoch 90/100
533/533 - 2s - 4ms/step - loss: 212653025490947276800.0000 - val_loss: 557622201109446656.0000
Epoch 91/100
533/533 - 2s - 3ms/step - loss: 212652955122203099136.0000 - val_loss: 557617768703197184.0000
Epoch 92/100
533/533 - 1s - 2ms/step - loss: 212652884753458921472.0000 - val_loss: 557613233217732608.0000
Epoch 93/100
533/533 - 1s - 2ms/step - loss: 212652761608156610560.0000 - val_loss: 557608113616715776.0000
Epoch 94/100
533/533 - 1s - 2ms/step - loss: 212653025490947276800.0000 - val_loss: 557603234533867520.0000
Epoch 95/100
533/533 - 1s - 2ms/step - loss: 212653043083133321216.0000 - val_loss: 557597908774420480.0000
Epoch 96/100
533/533 - 1s - 2ms/step - loss: 212652955122203099136.0000 - val_loss: 557592686094188544.0000
Epoch 97/100
533/533 - 1s - 2ms/step - loss: 212652937530017054720.0000 - val_loss: 557587154176311296.0000
Epoch 98/100
533/533 - 2s - 4ms/step - loss: 212652849569086832640.0000 - val_loss: 557581690977910784.0000
Epoch 99/100
533/533 - 2s - 5ms/step - loss: 212652919937831010304.0000 - val_loss: 557576227779510272.0000
Epoch 100/100
533/533 - 2s - 3ms/step - loss: 212652867161272877056.0000 - val_loss: 557569768148697088.0000