<a href="https://colab.research.google.com/github/Carrinson/collab-files/blob/main/timeseries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%pip install statsmodels

import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import adfuller

Requirement already satisfied: statsmodels in /usr/local/lib/python3.12/dist-packages (0.14.6)
Requirement already satisfied: numpy<3,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels) (2.0.2)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /usr/local/lib/python3.12/dist-packages (from statsmodels) (1.16.3)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in /usr/local/lib/python3.12/dist-packages (from statsmodels) (2.2.2)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels) (26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)

In [ ]:
popus = pd.read_csv("/content/2024_2026_bitcoin.csv")
popus.head()

             Timestamp     Open     High      Low    Close    Volume
0  2024-01-01 00:00:00  42652.0  42655.0  42651.0  42651.0  0.014804
1  2024-01-01 00:01:00  42626.0  42626.0  42620.0  42620.0  0.208011
2  2024-01-01 00:02:00  42616.0  42629.0  42616.0  42629.0  0.029365
3  2024-01-01 00:03:00  42639.0  42642.0  42634.0  42642.0  0.016249
4  2024-01-01 00:04:00  42661.0  42671.0  42655.0  42671.0  0.012124

In [ ]:
popus.tail()

                 Timestamp     Open     High      Low    Close     Volume
82489  2024-02-27 06:49:00  55356.0  55575.0  55320.0  55472.0  26.315552
82490  2024-02-27 06:50:00  55433.0  55458.0  55350.0  55426.0   2.132354
82491  2024-02-27 06:51:00  55415.0  55496.0  55415.0  55485.0   0.519853
82492  2024-02-27 06:52:00  55489.0  55489.0  55423.0  55437.0   0.073684
82493  2024-02-27 06:53:00  55451.0  55490.0    554.0      NaN        NaN

In [ ]:
# Test to see if stational
# if stationary less than 0 if not would be greater than 0

popus.columns = [col.lower() for col in popus.columns]

In [ ]:
popus.head()

             timestamp     open     high      low    close    volume
0  2024-01-01 00:00:00  42652.0  42655.0  42651.0  42651.0  0.014804
1  2024-01-01 00:01:00  42626.0  42626.0  42620.0  42620.0  0.208011
2  2024-01-01 00:02:00  42616.0  42629.0  42616.0  42629.0  0.029365
3  2024-01-01 00:03:00  42639.0  42642.0  42634.0  42642.0  0.016249
4  2024-01-01 00:04:00  42661.0  42671.0  42655.0  42671.0  0.012124

In [ ]:
popus['close'].isna().sum()

np.int64(1)

In [ ]:
popus.dropna(inplace=True)

In [ ]:
price_test_stationary = adfuller(popus['close'])

In [ ]:
print(f"The value is {price_test_stationary[0]}")
print(f"the p value {price_test_stationary[1]}")

The value is 0.19116812780101405
the p value 0.9717618679892635

In [ ]:
log_returns = np.log(popus['close'] / popus['close'].shift(1))

In [ ]:
log_returns.isna().sum()

np.int64(1)

In [ ]:
log_returns.dropna(inplace=True)

In [ ]:
log_returns_test_stationary = adfuller(log_returns)

In [ ]:
print(f"The value is {log_returns_test_stationary[0]}")
print(f"the p value {log_returns_test_stationary[1]}")

The value is -36.05193439739575
the p value 0.0

In [ ]:
popus['volume'].isna().sum()

np.int64(0)

In [ ]:
price_test_stationary = adfuller(popus['volume'])

In [ ]:
print(f"The value is {price_test_stationary[0]}")
print(f"the p value {price_test_stationary[1]}")

The value is -24.21559945879893
the p value 0.0

In [ ]:
log_returns = np.log(popus['volume'] / popus['volume'].shift(1))

In [ ]:
log_returns.isna().sum()

np.int64(143)

In [ ]:
log_returns.dropna(inplace=True)

In [ ]:
print(log_returns)

In [ ]:
log_returns_test_stationary = adfuller(log_returns)

MissingDataError: exog contains inf or nans

In [ ]:
print(f"The value is {log_returns_test_stationary[0]}")
print(f"the p value {log_returns_test_stationary[1]}")

In [ ]:
price_test_stationary = adfuller(popus['open'])

In [ ]:
print(f"the value is {price_test_stationary[0]}")
print(f"the value is {price_test_stationary[1]}")

In [ ]:
log_returns = np.long(popus['open'] / popus['open'].shift(1))

In [ ]:
log_returns.isna().sum()

In [ ]:
log_returns_test_stationary = adfuller(log_returns)

In [ ]:
print(f"the value is {log_returns_test_stationary[0]}")
print(f"the value is {log_returns_test_stationary[1]}")